import { PROJECT_DRAFT_SCHEMA_VERSION, type ProjectDraft } from "../project-draft";
import { MANUFACTURER_DRAFT_SCHEMA_VERSION, type ManufacturerApplicationDraft } from "../manufacturer-application-draft";

type Result<T>={ok:true;data:T}|{ok:false;errors:string[]};
const record=(value:unknown):value is Record<string,unknown>=>typeof value==="object"&&value!==null&&!Array.isArray(value);
const text=(value:unknown,max=10000)=>typeof value==="string"&&value.length<=max;
const texts=(value:unknown,maxItems=100)=>Array.isArray(value)&&value.length<=maxItems&&value.every(item=>text(item,200));
const uuid=(value:unknown)=>typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const zip=(value:unknown)=>typeof value==="string"&&/^\d{5}(-\d{4})?$/.test(value);

export function validateProjectDraft(value:unknown,final=false):Result<ProjectDraft>{const errors:string[]=[];if(!record(value)||!record(value.step1)||!record(value.step2)||!record(value.step3)||!record(value.step4))return{ok:false,errors:["Invalid project draft structure."]};if(value.schemaVersion!==PROJECT_DRAFT_SCHEMA_VERSION)errors.push("Unsupported project draft version.");if(!uuid(value.draftId))errors.push("Invalid project draft identifier.");const{s1,s2,s3,s4}={s1:value.step1,s2:value.step2,s3:value.step3,s4:value.step4};if(!text(s1.selectedCategory,100)||!text(s1.projectTitle,200)||!text(s1.description,10000)||!Array.isArray(s1.referenceImages))errors.push("Invalid product definition.");if(!text(s2.productType,300)||!text(s2.primaryDecision,300)||!texts(s2.materials)||!texts(s2.customizationOptions)||!texts(s2.complianceRequirements)||!texts(s2.printingFinishing)||!record(s2.dimensions)||!record(s2.size))errors.push("Invalid technical details.");if(!text(s3.orderQuantity,20)||!text(s3.minimumBudget,20)||!text(s3.maximumBudget,20)||s3.currency!=="USD"||!texts(s3.pricePriorities))errors.push("Invalid quantity or budget.");if(!text(s4.targetDeliveryDate,20)||!text(s4.shippingCity,100)||!text(s4.shippingState,2)||!text(s4.shippingZipCode,10)||s4.shippingCountry!=="United States")errors.push("Invalid timeline or shipping address.");const quantity=Number(s3.orderQuantity),min=Number(s3.minimumBudget||0),max=Number(s3.maximumBudget||0);if(s3.orderQuantity&&(!Number.isFinite(quantity)||quantity<=0))errors.push("Order quantity must be greater than 0.");if(s3.minimumBudget&&s3.maximumBudget&&min>max)errors.push("Minimum budget cannot exceed maximum budget.");if(final){if(!String(s1.selectedCategory).trim())errors.push("Select a product category.");if(!String(s1.projectTitle).trim())errors.push("Enter a project title.");if(!String(s1.description).trim())errors.push("Enter a product description.");if(!String(s2.productType).trim()||!String(s2.primaryDecision??"").trim())errors.push("Complete the required technical details.");if(!(quantity>0)||!String(s3.budgetType??"").trim())errors.push("Complete quantity and budget.");if(!String(s4.targetDeliveryDate).trim()||!String(s4.shippingCity).trim()||!String(s4.shippingState).trim()||!zip(s4.shippingZipCode))errors.push("Complete the U.S. shipping address and timeline.");}return errors.length?{ok:false,errors}:{ok:true,data:value as unknown as ProjectDraft};}

export function validateManufacturerDraft(value:unknown,final=false):Result<ManufacturerApplicationDraft>{const errors:string[]=[];if(!record(value)||!record(value.step1)||!record(value.step2)||!record(value.step3)||!record(value.step4))return{ok:false,errors:["Invalid manufacturer application structure."]};if(value.schemaVersion!==MANUFACTURER_DRAFT_SCHEMA_VERSION)errors.push("Unsupported manufacturer application version.");if(!uuid(value.draftId))errors.push("Invalid manufacturer application identifier.");const{s1,s2,s3,s4}={s1:value.step1,s2:value.step2,s3:value.step3,s4:value.step4};if(!text(s1.businessName,200)||!text(s1.businessEmail,320)||!texts(s1.supplierTypes)||!texts(s1.selectedCategories)||!text(s1.businessCity,100)||!text(s1.businessState,2)||!text(s1.businessZipCode,10))errors.push("Invalid business profile.");if(!texts(s2.packagingTypes)||!texts(s2.materials)||!texts(s2.printingMethods)||!texts(s2.finishingCapabilities)||!texts(s2.fillingCapabilities)||!texts(s2.industriesServed))errors.push("Invalid capabilities.");if(!texts(s3.shippingRegions)||!texts(s3.shippingStates)||!text(s3.facilityCity,100)||!text(s3.facilityState,2)||!text(s3.facilityZipCode,10))errors.push("Invalid operations data.");if(!text(s4.legalBusinessName,200)||!text(s4.businessAddress,1000)||!texts(s4.certifications)||!Array.isArray(s4.documents))errors.push("Invalid verification data.");if(final){if(!String(s1.businessName).trim()||!String(s1.contactPerson??"").trim()||!/^\S+@\S+\.\S+$/.test(String(s1.businessEmail)))errors.push("Complete the required business information.");if(!(s1.supplierTypes as unknown[]).length||!zip(s1.businessZipCode))errors.push("Complete supplier type and business location.");if(!(s2.packagingTypes as unknown[]).length||!(s2.materials as unknown[]).length||!(s2.industriesServed as unknown[]).length)errors.push("Complete the required production capabilities.");if(!(Number(s3.minimumOrderQuantity)>0)||!(Number(s3.maximumOrderCapacity)>0)||!(Number(s3.monthlyCapacity)>0)||!(s3.shippingRegions as unknown[]).length||!zip(s3.facilityZipCode))errors.push("Complete capacity, facility, and shipping coverage.");if(!String(s4.legalBusinessName).trim()||!String(s4.registrationNumber??"").trim()||!String(s4.businessAddress).trim()||!String(s4.contactPhone??"").trim()||s4.insuranceConfirmed!==true||s4.termsConfirmed!==true)errors.push("Complete verification and required confirmations.");}return errors.length?{ok:false,errors}:{ok:true,data:value as unknown as ManufacturerApplicationDraft};}
