"use client";
import { useEffect,useRef,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import Header from "../../../components/Header";
import { createEmptyProjectDraft,readProjectDraft,writeProjectDraft,type ProjectStep2 } from "../../../lib/project-draft";
import { getMarketplaceCategoryBySlug,resolveMarketplaceCategorySlug,type MarketplaceCategorySlug } from "../../../lib/us-marketplace-taxonomy";
import { PROJECT_SPECIFICATIONS,validateProjectSpecifications } from "../../../lib/project-specifications";

const card="min-w-0 rounded-[32px] border border-[#E5E0D8] bg-white p-6 shadow-sm sm:p-8";
function Progress(){return <div className="mb-12 max-w-full overflow-x-auto overscroll-x-contain"><div className="flex w-max min-w-[850px] rounded-2xl border border-[#E5E0D8] bg-white p-5">{["Product Category","Technical Details","Quantity & Budget","Timeline","Review"].map((x,i)=><div className="flex flex-1 items-center" key={x}><span className={`mr-3 grid h-8 w-8 place-items-center rounded-full ${i<2?"bg-[#7C8A6A] text-white":"border border-[#E5E0D8]"}`}>{i+1}</span><span className={i<2?"font-bold":"text-[#7C7A74]"}>{x}</span>{i<4?<span className="mx-4 h-px flex-1 bg-[#E5E0D8]"/>:null}</div>)}</div></div>}
function Radios({label,options,value,set,error,refProp}:{label:string;options:readonly string[];value:string;set:(x:string)=>void;error?:string;refProp?:React.RefObject<HTMLFieldSetElement|null>}){const id=label.replace(/\W/g,"-");return <fieldset ref={refProp} tabIndex={-1} aria-describedby={error?id+"-error":undefined} className={`${card} ${error?"border-[#C9826B] ring-1 ring-[#C9826B]/30":""}`}><legend className="px-2 text-lg font-bold">{label}<span className="ml-2 text-xs uppercase tracking-widest text-[#7A3F31]">Required</span></legend><div className="mt-4 grid gap-3 sm:grid-cols-2">{options.map(x=><label key={x} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-4 text-sm font-semibold ${value===x?"border-[#7C8A6A] bg-[#EEF1E8]":"border-[#E5E0D8]"}`}><input type="radio" name={id} checked={value===x} onChange={()=>set(x)} className="accent-[#7C8A6A]"/>{x}<span className="ml-auto" aria-hidden>{value===x?"✓":""}</span></label>)}</div>{error?<p id={id+"-error"} role="alert" className="mt-3 text-sm text-[#7A3F31]">{error}</p>:null}</fieldset>}
function Checks({label,options,value,set}:{label:string;options:readonly string[];value:string[];set:(x:string[])=>void}){return <fieldset className={card}><legend className="px-2 text-lg font-bold">{label}</legend><div className="mt-4 grid gap-3 sm:grid-cols-2">{options.map(x=>{const on=value.includes(x);return <label key={x} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-4 text-sm font-semibold ${on?"border-[#7C8A6A] bg-[#EEF1E8]":"border-[#E5E0D8]"}`}><input type="checkbox" checked={on} onChange={()=>set(on?value.filter(v=>v!==x):[...value,x])} className="accent-[#7C8A6A]"/>{x}<span className="ml-auto" aria-hidden>{on?"✓":""}</span></label>})}</div></fieldset>}
export default function Page(){const router=useRouter(),first=useRef<HTMLFieldSetElement>(null),second=useRef<HTMLFieldSetElement>(null);const [step,setStep]=useState<ProjectStep2>(()=>createEmptyProjectDraft().step2),[slug,setSlug]=useState<MarketplaceCategorySlug|null>(null),[ready,setReady]=useState(false),[attempted,setAttempted]=useState(false),[saved,setSaved]=useState(false);
useEffect(()=>{const draft=readProjectDraft(),s=resolveMarketplaceCategorySlug(draft?.step1.selectedCategory);
// Initial hydration intentionally synchronizes state with the browser-only draft store.
// eslint-disable-next-line react-hooks/set-state-in-effect
setSlug(s);setStep(draft&&draft.step2.categorySlug===s?draft.step2:{...createEmptyProjectDraft().step2,categorySlug:s??""});setReady(true)},[]);
useEffect(()=>{if(!ready)return;const t=setTimeout(()=>writeProjectDraft({step2:step}),600);return()=>clearTimeout(t)},[step,ready]);
const update=<K extends keyof ProjectStep2>(k:K,v:ProjectStep2[K])=>{setStep(s=>({...s,[k]:v}));setSaved(false)},errors=validateProjectSpecifications(step),config=slug?PROJECT_SPECIFICATIONS[slug]:null,category=getMarketplaceCategoryBySlug(slug);
const next=()=>{setAttempted(true);if(errors.productType||errors.primaryDecision){(errors.productType?first:second).current?.focus();return}writeProjectDraft({step2:step});router.push("/post-project/quantity-budget")};
if(!config)return <div className="min-h-screen bg-[#F6F3EE]"><Header/><main className="mx-auto max-w-3xl px-6 pt-36"><div className={card}><h1 className="text-3xl font-bold">Choose a product category first</h1><Link className="mt-6 inline-block rounded-full bg-[#7C8A6A] px-6 py-3 text-white" href="/post-project">Choose category</Link></div></main></div>;
return <div className="min-h-screen bg-[#F6F3EE] text-[#1F2937]"><Header/><main className="mx-auto w-full min-w-0 max-w-7xl px-4 pb-24 pt-32 sm:px-8"><Progress/><header className="mb-10"><div className="flex min-w-0 flex-wrap gap-3 text-sm"><strong className="rounded-full bg-[#EEF1E8] px-4 py-2 text-[#667255]">{category?.name}</strong><Link className="py-2 font-semibold text-[#7C8A6A] underline" href="/post-project">Change category</Link></div><h1 className="mt-6 break-words text-3xl font-bold sm:text-4xl text-[#111111]">Define your product specifications</h1><p className="mt-4 text-lg text-[#7C7A74]">Add what you know now. Maker guidance is a valid choice when a decision is still open.</p></header><div className="space-y-6">
<Radios refProp={first} label={config.productLabel} options={config.productOptions} value={step.productType} set={v=>update("productType",v)} error={attempted?errors.productType:""}/><Radios refProp={second} label={config.primaryLabel} options={config.primaryOptions} value={step.primaryDecision} set={v=>update("primaryDecision",v)} error={attempted?errors.primaryDecision:""}/>
{config.secondaryLabel&&config.secondaryOptions?<Radios label={config.secondaryLabel} options={config.secondaryOptions} value={step.secondaryDecision} set={v=>update("secondaryDecision",v)}/>:null}
{config.textLabel?<label className={`${card} block text-lg font-bold`}>{config.textLabel} <span className="text-sm font-normal text-[#7C7A74]">(optional)</span><textarea className="mt-4 min-h-28 w-full rounded-2xl border border-[#E5E0D8] p-4 text-sm font-normal" value={step.textDetail} onChange={e=>update("textDetail",e.target.value)}/></label>:null}
{config.sizeLabel?<section className={card}><h2 className="text-lg font-bold">{config.sizeLabel} <span className="text-sm font-normal text-[#7C7A74]">(optional)</span></h2><div className="mt-4 grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-[minmax(0,1fr)_auto]"><input aria-label="Size value" className="rounded-2xl border border-[#E5E0D8] p-4" value={step.size.value} onChange={e=>update("size",{...step.size,value:e.target.value})}/><select aria-label="Size unit" className="rounded-2xl border border-[#E5E0D8] bg-white p-4" value={step.size.unit} onChange={e=>update("size",{...step.size,unit:e.target.value})}><option value="">Unit</option>{config.sizeUnits?.map(x=><option key={x}>{x}</option>)}</select></div></section>:null}
{config.dimensions?<section className={card}><h2 className="text-lg font-bold">Dimensions <span className="text-sm font-normal text-[#7C7A74]">(optional)</span></h2><div className="mt-4 grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-4">{(["length","width","height"] as const).map(k=><input key={k} aria-label={k} placeholder={k} className="rounded-2xl border border-[#E5E0D8] p-4" value={step.dimensions[k]} onChange={e=>update("dimensions",{...step.dimensions,[k]:e.target.value})}/>) }<select aria-label="Dimension unit" className="rounded-2xl border border-[#E5E0D8] bg-white p-4" value={step.dimensions.unit} onChange={e=>update("dimensions",{...step.dimensions,unit:e.target.value})}>{config.dimensionUnits?.map(x=><option key={x}>{x}</option>)}</select></div></section>:null}
{config.printingOptions?<Checks label="Printing and finishing" options={config.printingOptions} value={step.printingFinishing} set={v=>update("printingFinishing",v)}/>:null}{config.customizationLabel&&config.customizationOptions?<Checks label={config.customizationLabel} options={config.customizationOptions} value={step.customizationOptions} set={v=>update("customizationOptions",v)}/>:null}{config.requirementsLabel&&config.requirementsOptions?<Checks label={config.requirementsLabel} options={config.requirementsOptions} value={step.complianceRequirements} set={v=>update("complianceRequirements",v)}/>:null}
<label className={`${card} block text-lg font-bold`}>Additional technical notes <span className="text-sm font-normal text-[#7C7A74]">(optional)</span><textarea className="mt-4 min-h-32 w-full rounded-2xl border border-[#E5E0D8] p-4 text-sm font-normal" value={step.additionalNotes} onChange={e=>update("additionalNotes",e.target.value)}/></label></div>
<div className="mt-10 flex min-w-0 flex-col gap-3 sm:flex-row sm:justify-between"><Link href="/post-project" className="rounded-full border border-[#E5E0D8] bg-white px-8 py-4 text-center font-bold">Back</Link><div className="flex min-w-0 flex-col gap-3 sm:flex-row">{saved?<p role="status" className="self-center text-sm text-[#667255]">Draft saved on this device.</p>:null}<button className="rounded-full border border-[#7C8A6A] px-8 py-4 font-bold text-[#667255]" onClick={()=>{writeProjectDraft({step2:step});setSaved(true)}}>Save as draft</button><button className="rounded-full bg-[#7C8A6A] px-8 py-4 font-bold text-white" onClick={next}>Next Step</button></div></div></main></div>}
