"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import Header from "../../../components/Header";
import ManufacturerApplicationProgress from "../../../components/ManufacturerApplicationProgress";
import { MANUFACTURER_APPLICATION_DRAFT_STORAGE_KEY, createEmptyManufacturerApplicationDraft, readManufacturerApplicationDraft, writeManufacturerApplicationDraft, type ManufacturerApplicationStep1 } from "../../../lib/manufacturer-application-draft";
import { PRODUCT_CATEGORIES, SUPPLIER_TYPES, US_STATES } from "../../../lib/us-marketplace-taxonomy";

const categories=[...PRODUCT_CATEGORIES];
type FilePreview={id:string;url:string;name:string;isPdf:boolean};
type RequiredField="businessName"|"contactPerson"|"businessEmail"|"businessCity"|"businessState"|"businessZipCode"|"supplierTypes"|"selectedCategories"|"minimumOrderQuantity"|"typicalLeadTime"|"capabilitiesDescription";

export default function ManufacturerApplyPage(){
  const router=useRouter();
  const [step1,setStep1]=useState<ManufacturerApplicationStep1>(()=>createEmptyManufacturerApplicationDraft().step1);
  const [previews,setPreviews]=useState<FilePreview[]>([]);
  const [message,setMessage]=useState<string|null>(null);
  const [attempted,setAttempted]=useState(false);
  const refs=useRef<Partial<Record<RequiredField,HTMLElement|null>>>({});
  const fileInputRef=useRef<HTMLInputElement>(null);
  const reset=useCallback(()=>{setStep1(createEmptyManufacturerApplicationDraft().step1);setPreviews(current=>{current.forEach(item=>URL.revokeObjectURL(item.url));return[]});if(fileInputRef.current)fileInputRef.current.value="";setAttempted(false);setMessage(null)},[]);
  useEffect(()=>{const isNew=new URLSearchParams(window.location.search).get("new")==="1";if(isNew){window.localStorage.removeItem(MANUFACTURER_APPLICATION_DRAFT_STORAGE_KEY);reset();router.replace("/for-manufacturers/apply");return}const draft=readManufacturerApplicationDraft();if(draft)setStep1(draft.step1)},[reset,router]);
  useEffect(()=>()=>{previews.forEach(item=>URL.revokeObjectURL(item.url))},[previews]);
  useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(null),3500);return()=>clearTimeout(timer)},[message]);
  const update=<K extends keyof ManufacturerApplicationStep1>(field:K,value:ManufacturerApplicationStep1[K])=>setStep1(current=>({...current,[field]:value}));
  const toggleCategory=(category:string)=>update("selectedCategories",step1.selectedCategories.includes(category)?step1.selectedCategories.filter(item=>item!==category):[...step1.selectedCategories,category]);
  const addFiles=(files:FileList|null)=>{if(!files)return;setPreviews(current=>[...current,...Array.from(files).map(file=>({id:`${file.name}-${file.size}-${file.lastModified}`,url:URL.createObjectURL(file),name:file.name,isPdf:file.type==="application/pdf"}))])};
  const persistedStep=():ManufacturerApplicationStep1=>({...step1,portfolioImages:previews.length?previews.map(({name,isPdf})=>({name,isPdf})):step1.portfolioImages});
  const errors:Record<RequiredField,string>={businessName:step1.businessName.trim()?"":"Enter your business name.",contactPerson:step1.contactPerson.trim()?"":"Enter a contact person.",businessEmail:/\S+@\S+\.\S+/.test(step1.businessEmail)?"":"Enter a valid business email.",businessCity:step1.businessCity.trim()?"":"Enter the business city.",businessState:step1.businessState?"":"Select the business state.",businessZipCode:/^\d{5}(-\d{4})?$/.test(step1.businessZipCode)?"":"Enter a valid ZIP code.",supplierTypes:step1.supplierTypes.length?"":"Select at least one supplier type.",selectedCategories:step1.selectedCategories.length?"":"Select at least one industry.",minimumOrderQuantity:Number(step1.minimumOrderQuantity)>0?"":"Enter a typical MOQ greater than 0.",typicalLeadTime:step1.typicalLeadTime.trim()?"":"Enter a typical lead time.",capabilitiesDescription:step1.capabilitiesDescription.trim()?"":"Describe your manufacturing capabilities."};
  const invalid=(field:RequiredField)=>attempted&&Boolean(errors[field]);
  const fieldClass=(field:RequiredField)=>`h-14 w-full rounded-2xl border bg-[#F6F3EE]/70 px-4 text-base text-[#111111] outline-none transition focus:ring-4 ${invalid(field)?"border-[#C9826B] bg-[#F5E6E0]/30 focus:ring-[#C9826B]/10":"border-[#E5E0D8] focus:border-[#7C8A6A] focus:ring-[#7C8A6A]/10"}`;
  const error=(field:RequiredField)=>invalid(field)?<p id={`${field}-error`} className="mt-2 text-sm text-[#C9826B]">{errors[field]}</p>:null;
  const aria=(field:RequiredField)=>({"aria-invalid":invalid(field)||undefined,"aria-describedby":invalid(field)?`${field}-error`:undefined});
  const save=()=>{writeManufacturerApplicationDraft({step1:persistedStep()});setMessage("Draft saved locally.")};
  const next=()=>{setAttempted(true);const first=(Object.keys(errors)as RequiredField[]).find(field=>errors[field]);if(first){setTimeout(()=>{refs.current[first]?.scrollIntoView({behavior:"smooth",block:"center"});refs.current[first]?.focus()},0);return}writeManufacturerApplicationDraft({step1:persistedStep()});router.push("/for-manufacturers/apply/capabilities")};
  const label="mb-3 block text-[13px] font-semibold uppercase tracking-[0.18em] text-[#1F2937]";
  const input=(field:RequiredField,value:string,onChange:(value:string)=>void,type="text")=><><input ref={node=>{refs.current[field]=node}} type={type} value={value} onChange={event=>onChange(event.target.value)} className={fieldClass(field)} {...aria(field)}/>{error(field)}</>;
  return <div className="min-h-screen overflow-x-hidden bg-[#F6F3EE] text-[#1F2937]"><Header/><main className="mx-auto w-full max-w-[1220px] px-4 pb-20 pt-20 sm:px-6 sm:pt-24"><ManufacturerApplicationProgress activeStep={1}/><div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_340px] lg:items-start"><div><section className="rounded-[32px] border border-[#E5E0D8] bg-white p-6 shadow-sm sm:p-10 lg:p-12"><header className="max-w-[620px] pb-8"><h1 className="text-4xl font-semibold tracking-tight text-[#111111] sm:text-5xl">Join BatchNGo as a manufacturer</h1><p className="mt-5 text-base leading-8 text-[#7C7A74] sm:text-lg">Tell us about your business, capabilities and the products you manufacture.</p></header><div className="grid gap-6">
    <div><label className={label}>Business name · Required</label>{input("businessName",step1.businessName,value=>update("businessName",value))}</div>
    <div className="grid gap-6 md:grid-cols-2"><div><label className={label}>Contact person · Required</label>{input("contactPerson",step1.contactPerson,value=>update("contactPerson",value))}</div><div><label className={label}>Business email · Required</label>{input("businessEmail",step1.businessEmail,value=>update("businessEmail",value),"email")}</div></div>
    <div><p className={label}>Business location · Required</p><div className="grid gap-4 sm:grid-cols-2"><div>{input("businessCity",step1.businessCity,value=>update("businessCity",value))}</div><div><select ref={node=>{refs.current.businessState=node}} value={step1.businessState} onChange={e=>update("businessState",e.target.value)} className={fieldClass("businessState")} {...aria("businessState")}><option value="">Select state</option>{US_STATES.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select>{error("businessState")}</div><div>{input("businessZipCode",step1.businessZipCode,value=>update("businessZipCode",value))}</div><input value="United States" readOnly aria-label="Business country" className="h-14 w-full rounded-2xl border border-[#E5E0D8] bg-[#F6F3EE]/70 px-4 text-[#7C7A74]"/></div></div>
    <div><label className={label}>Website or social profile · Optional</label><input type="url" value={step1.website} onChange={event=>update("website",event.target.value)} className={fieldClass("businessName").replace("border-[#C9826B] bg-[#F5E6E0]/30 focus:ring-[#C9826B]/10","border-[#E5E0D8] focus:border-[#7C8A6A] focus:ring-[#7C8A6A]/10")}/></div>
    <div ref={node=>{refs.current.supplierTypes=node}} tabIndex={-1} className={`rounded-2xl outline-none ${invalid("supplierTypes")?"ring-2 ring-[#C9826B]/40":""}`} {...aria("supplierTypes")}><p className={label}>Supplier type · Required</p><div className="grid gap-3 sm:grid-cols-3">{SUPPLIER_TYPES.map(type=><label key={type} className="flex gap-3 rounded-2xl border border-[#E5E0D8] p-4 text-sm"><input type="checkbox" checked={step1.supplierTypes.includes(type)} onChange={()=>update("supplierTypes",step1.supplierTypes.includes(type)?step1.supplierTypes.filter(item=>item!==type):[...step1.supplierTypes,type])}/>{type}</label>)}</div>{error("supplierTypes")}</div>
    <div ref={node=>{refs.current.selectedCategories=node}} tabIndex={-1} className={`rounded-2xl outline-none ${invalid("selectedCategories")?"ring-2 ring-[#C9826B]/40":""}`} {...aria("selectedCategories")}><p className={label}>Product categories · Required</p><div className="grid gap-3 sm:grid-cols-2">{categories.map(category=><button type="button" key={category} onClick={()=>toggleCategory(category)} className={`flex min-w-0 items-center justify-between rounded-[24px] border p-5 text-left text-sm ${step1.selectedCategories.includes(category)?"border-[#7C8A6A] bg-[#EEF1E8] text-[#111111]":"border-[#E5E0D8] bg-white text-[#7C7A74]"}`}><span>{category}</span>{step1.selectedCategories.includes(category)?<span aria-hidden="true">✓</span>:null}</button>)}</div>{error("selectedCategories")}</div>
    <div className="grid gap-6 md:grid-cols-2"><div><label className={label}>Minimum order quantity · Required</label>{input("minimumOrderQuantity",step1.minimumOrderQuantity,value=>update("minimumOrderQuantity",value),"number")}</div><div><label className={label}>Typical lead time · Required</label>{input("typicalLeadTime",step1.typicalLeadTime,value=>update("typicalLeadTime",value))}</div></div>
    <div><label className={label}>Manufacturing capabilities · Required</label><textarea ref={node=>{refs.current.capabilitiesDescription=node}} rows={7} value={step1.capabilitiesDescription} onChange={event=>update("capabilitiesDescription",event.target.value)} className={`${fieldClass("capabilitiesDescription")} min-h-[180px] resize-y py-5 leading-8`} {...aria("capabilitiesDescription")}/>{error("capabilitiesDescription")}</div>
    <div><p className={label}>U.S. operations and origin information</p><div className="grid gap-3"><label className="flex gap-3 rounded-2xl border border-[#E5E0D8] p-4"><input type="checkbox" checked={step1.usBasedCompany} onChange={e=>update("usBasedCompany",e.target.checked)}/>U.S.-based company</label><label className="flex gap-3 rounded-2xl border border-[#E5E0D8] p-4"><input type="checkbox" checked={step1.usManufacturing} onChange={e=>update("usManufacturing",e.target.checked)}/>Manufacturing is performed in the United States</label><label className={label}>Origin claim supplied by the manufacturer · Optional</label><input value={step1.originClaim} onChange={e=>update("originClaim",e.target.value)} placeholder="Describe the exact origin claim you can support" className="h-14 w-full rounded-2xl border border-[#E5E0D8] bg-[#F6F3EE]/70 px-4"/></div></div>
    <div><label className={label}>Portfolio images · Optional</label><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><button type="button" onClick={()=>fileInputRef.current?.click()} className="flex h-[120px] flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#E5E0D8] bg-[#F6F3EE]/50 text-[#7C7A74]"><span className="text-3xl">+</span><span className="text-sm font-semibold">Add image</span></button>{previews.slice(0,2).map(item=><div key={item.id} className="relative h-[120px] overflow-hidden rounded-2xl border border-[#E5E0D8] bg-[#F6F3EE]">{item.isPdf?<span className="flex h-full items-center justify-center text-sm">{item.name}</span>:<Image src={item.url} alt={item.name} fill sizes="240px" className="object-cover"/>}</div>)}</div><input ref={fileInputRef} type="file" accept="image/png,image/jpeg,image/jpg,application/pdf" multiple className="hidden" onChange={event=>addFiles(event.target.files)}/></div>
  </div></section><div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><button type="button" onClick={save} className="rounded-full border border-[#E5E0D8] bg-white px-8 py-4 text-sm font-bold uppercase tracking-widest text-[#7C7A74]">Save as draft</button><button type="button" onClick={next} className="rounded-full bg-[#7C8A6A] px-8 py-4 text-sm font-bold uppercase tracking-widest text-white">Continue</button></div>{message?<div role="status" className="mt-4 rounded-2xl border border-[#7C8A6A] bg-[#EEF1E8] px-6 py-4 text-sm">{message}</div>:null}</div><aside className="lg:sticky lg:top-24"><div className="rounded-[28px] border border-[#E5E0D8] bg-white p-8 shadow-sm"><h3 className="text-xl font-semibold text-[#111111]">Why join BatchNGo?</h3><ul className="mt-6 space-y-5 text-sm text-[#7C7A74]">{["Receive qualified production requests","Choose which projects to quote","Set your own MOQ and lead times","Showcase your portfolio","Build trust through verification"].map(item=><li key={item} className="flex gap-3"><span className="text-[#7C8A6A]" aria-hidden="true">✓</span><span>{item}</span></li>)}</ul></div></aside></div></main></div>;
}
