import Link from "next/link";
import { notFound } from "next/navigation";
import { NoteControl, StatusControl } from "../../../../components/admin/AdminControls";
import { getAdminContext, isUuid } from "../../../../lib/admin/server";
import type { Json } from "../../../../lib/supabase/database.types";

const object = (input: Json | undefined): Record<string, Json | undefined> => typeof input === "object" && input !== null && !Array.isArray(input) ? input : {};
const display = (input: Json | undefined): string => Array.isArray(input) ? input.join(", ") : typeof input === "boolean" ? (input ? "Yes" : "No") : typeof input === "string" || typeof input === "number" ? String(input) : "—";

export default async function ManufacturerApplicationDetail({ params }: { params: Promise<{ id: string }> }) {
  const context = await getAdminContext(); if (!context.ok) return null;
  const { id } = await params; if (!isUuid(id)) notFound();
  const [applicationResult, noteResult] = await Promise.all([
    context.admin.from("manufacturer_applications").select("*").eq("id", id).maybeSingle(),
    context.admin.from("admin_notes").select("note").eq("entity_type", "manufacturer_application").eq("entity_id", id).limit(1),
  ]);
  const application = applicationResult.data; if (!application) notFound();
  const notes = noteResult.data ?? [];
  const draft = object(object(application.application_data).draft), s1 = object(draft.step1), s2 = object(draft.step2), s3 = object(draft.step3), s4 = object(draft.step4);
  return <main className="mx-auto max-w-[1400px] px-5 py-10 sm:px-8"><Link href="/admin/manufacturers" className="text-sm font-bold text-[#667255]">← Back to applications</Link><div className="mt-5 grid gap-8 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-6"><header><h1 className="text-4xl font-semibold">{display(s1.businessName)}</h1><p className="mt-3 text-[#7C7A74]">Submitted {application.submitted_at ? new Date(application.submitted_at).toLocaleString("en-US") : "as a draft"}</p></header><Section title="Business profile" data={[["Contact",display(s1.contactPerson)],["Email",display(s1.businessEmail)],["Supplier types",display(s1.supplierTypes)],["Categories",display(s1.selectedCategories)],["Business location",[display(s1.businessCity),display(s1.businessState),display(s1.businessZipCode)].join(", ")],["U.S.-based company",display(s1.usBasedCompany)],["U.S. manufacturing",display(s1.usManufacturing)],["Origin claim",display(s1.originClaim)]]}/><Section title="Capabilities" data={[["Packaging types",display(s2.packagingTypes)],["Materials",display(s2.materials)],["Printing",display(s2.printingMethods)],["Finishing",display(s2.finishingCapabilities)],["Filling",display(s2.fillingCapabilities)],["Assembly & kitting",display(s2.assemblyAndKitting)],["Industries",display(s2.industriesServed)],["Certifications",display(s2.certifications)]]}/><Section title="Operations" data={[["Typical MOQ",display(s3.minimumOrderQuantity)],["Maximum order",display(s3.maximumOrderCapacity)],["Monthly capacity",display(s3.monthlyCapacity)],["Lead time",display(s3.typicalLeadTime)],["Shipping regions",display(s3.shippingRegions)],["Shipping states",display(s3.shippingStates)],["Facility",[display(s3.facilityCity),display(s3.facilityState),display(s3.facilityZipCode)].join(", ")],["Team / years",`${display(s3.teamSize)} / ${display(s3.yearsInBusiness)}`]]}/><Section title="Verification" data={[["Legal name",display(s4.legalBusinessName)],["Registration",display(s4.registrationNumber)],["Tax number",display(s4.taxNumber)],["Address",display(s4.businessAddress)],["Phone",display(s4.contactPhone)],["Insurance confirmed",display(s4.insuranceConfirmed)],["Terms confirmed",display(s4.termsConfirmed)],["Documents",Array.isArray(s4.documents)?`${s4.documents.length} uploaded metadata records`:"None"]]}/></div><aside className="space-y-6"><div className="rounded-[24px] border border-[#E5E0D8] bg-white p-5"><StatusControl endpoint={`/api/admin/manufacturer-applications/${id}`} initialStatus={application.status} options={["submitted","under_review","approved","rejected"]}/><p className="mt-4 text-xs leading-5 text-[#7C7A74]">Approving creates or updates the public manufacturer profile. No “Made in USA” claim is inferred.</p></div><div className="rounded-[24px] border border-[#E5E0D8] bg-white p-5"><NoteControl endpoint={`/api/admin/manufacturer-applications/${id}`} initialNote={notes[0]?.note||""}/></div></aside></div></main>;
}
function Section({title,data}:{title:string;data:Array<[string,string]>}){return <section className="rounded-[24px] border border-[#E5E0D8] bg-white p-6"><h2 className="mb-5 text-xl font-semibold">{title}</h2><dl className="grid gap-5 sm:grid-cols-2">{data.map(([label,value])=><div key={label}><dt className="text-xs font-bold uppercase tracking-wider text-[#7C7A74]">{label}</dt><dd className="mt-2 break-words text-sm leading-6">{value}</dd></div>)}</dl></section>}
