import Link from "next/link";
import { getAdminContext } from "../../../lib/admin/server";
import type { Json } from "../../../lib/supabase/database.types";
import { PRODUCT_CATEGORIES, US_STATES } from "../../../lib/us-marketplace-taxonomy";

const object = (value: Json | undefined): Record<string, Json | undefined> => typeof value === "object" && value !== null && !Array.isArray(value) ? value : {};
const value = (input: Json | undefined) => typeof input === "string" || typeof input === "number" ? String(input) : "";

export default async function AdminProjectsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await getAdminContext(); if (!context.ok) return null;
  const filters = await searchParams;
  const { data } = await context.admin.from("projects").select("*").order("submitted_at", { ascending: false }).limit(250);
  const projects = (data ?? []).filter((project) => {
    const details = object(project.technical_details), draft = object(details.draft), step1 = object(draft.step1), step3 = object(draft.step3), step4 = object(draft.step4);
    const category = value(step1.selectedCategory), state = value(step4.shippingState) || value(object(project.shipping_address).state), deadline = value(step4.targetDeliveryDate), moq = Number(project.quantity || value(step3.orderQuantity) || 0);
    return (!filters.status || project.status === filters.status) && (!filters.category || category === filters.category) && (!filters.state || state === filters.state) && (!filters.moq || moq >= Number(filters.moq)) && (!filters.deadline || (!!deadline && deadline <= filters.deadline));
  });
  return <main className="mx-auto max-w-[1500px] px-5 py-10 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#7C8A6A]">Operations queue</p><h1 className="mt-2 text-4xl font-semibold">Projects</h1></div><p className="text-sm text-[#7C7A74]">{projects.length} results</p></div><form className="mt-8 grid gap-3 rounded-[24px] border border-[#E5E0D8] bg-white p-5 md:grid-cols-6"><Filter name="status" label="Status" value={filters.status} options={["submitted","under_review","matched","closed","rejected","draft"]}/><Filter name="category" label="Category" value={filters.category} options={[...PRODUCT_CATEGORIES]}/><Filter name="state" label="State" value={filters.state} options={US_STATES.map(([code,name]) => ({value:code,label:name}))}/><Field name="moq" label="Minimum quantity" value={filters.moq} type="number"/><Field name="deadline" label="Deadline by" value={filters.deadline} type="date"/><div className="flex items-end gap-2"><button className="h-11 flex-1 rounded-full bg-[#7C8A6A] px-4 text-sm font-bold text-white">Filter</button><Link href="/admin/projects" className="flex h-11 items-center rounded-full border border-[#E5E0D8] px-4 text-sm font-bold">Clear</Link></div></form><div className="mt-6 overflow-x-auto rounded-[24px] border border-[#E5E0D8] bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#EEEAE3] text-xs uppercase tracking-wider text-[#7C7A74]"><tr><th className="p-4">Project</th><th className="p-4">Status</th><th className="p-4">Category</th><th className="p-4">Quantity</th><th className="p-4">State</th><th className="p-4">Deadline</th><th className="p-4">Submitted</th></tr></thead><tbody>{projects.map((project) => { const draft=object(object(project.technical_details).draft),s1=object(draft.step1),s4=object(draft.step4);return <tr key={project.id} className="border-t border-[#E5E0D8] hover:bg-[#F9F7F3]"><td className="p-4"><Link className="font-bold underline decoration-[#7C8A6A]/40" href={`/admin/projects/${project.id}`}>{project.title}</Link><span className="mt-1 block max-w-xs truncate text-xs text-[#7C7A74]">{project.description}</span></td><td className="p-4"><Badge>{project.status}</Badge></td><td className="p-4">{value(s1.selectedCategory) || "—"}</td><td className="p-4">{project.quantity || "—"}</td><td className="p-4">{value(s4.shippingState) || "—"}</td><td className="p-4">{value(s4.targetDeliveryDate) || "—"}</td><td className="p-4">{project.submitted_at ? new Date(project.submitted_at).toLocaleDateString("en-US") : "Draft"}</td></tr>})}</tbody></table>{!projects.length ? <p className="p-10 text-center text-sm text-[#7C7A74]">No projects match these filters.</p> : null}</div></main>;
}
function Badge({children}:{children:string}){return <span className="rounded-full bg-[#EEF1E8] px-3 py-1 text-xs font-bold text-[#667255]">{children.replaceAll("_"," ")}</span>}
function Field({name,label,value:current,type}:{name:string;label:string;value?:string;type:string}){return <label className="text-xs font-bold uppercase tracking-wider text-[#7C7A74]">{label}<input name={name} defaultValue={current} type={type} min={type==="number"?1:undefined} className="mt-2 h-11 w-full rounded-xl border border-[#E5E0D8] px-3 text-sm font-normal normal-case"/></label>}
function Filter({name,label,value:current,options}:{name:string;label:string;value?:string;options:Array<string|{value:string;label:string}>}){return <label className="text-xs font-bold uppercase tracking-wider text-[#7C7A74]">{label}<select name={name} defaultValue={current||""} className="mt-2 h-11 w-full rounded-xl border border-[#E5E0D8] bg-white px-3 text-sm font-normal normal-case"><option value="">All</option>{options.map((option)=>{const entry=typeof option==="string"?{value:option,label:option}:option;return <option key={entry.value} value={entry.value}>{entry.label}</option>})}</select></label>}
